name: Notify

on:
  schedule:
    - cron: '13 12 * * *'

# on: [push]

permissions:
  contents: write

env:
  PUSHKEY:  ${{ secrets.PUSHKEY }}
  CONTENT:  ${{ secrets.CONTENT }}
  TITLE_HAX:   ${{ secrets.TITLE_HAX }}
  TITLE_VC:   ${{ secrets.TITLE_VC }}
  DAY:      ${{ secrets.DAY }}

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run Script
      run: python run.py

    - name: Commit and push changes
      run: |
        git config --local user.name 'Garfyyy'
        git config --local user.email 'garfy@stu.gxnu.edu.cn'
        git add .
        git diff --exit-code && git commit -m "update result"
        git push origin main
