name: Notify

# on:
#   schedule:
#     - cron: '0 12 */5 * *'
#     - cron: '0 12 */7 * *'

on: [push]

env:
  PUSHKEY: ${{ secrets.PUSHKEY }}
  CONTENT: ${{ secrets.CONTENT }}
  TITLE1: ${{ secrets.TITLE1 }}
  TITLE2: ${{ secrets.TITLE2 }}
  DAY1: ${{ secrets.DAY1 }}
  DAY2: ${{ secrets.DAY2 }}

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Send msgs1
      if: github.event_name == 'push' || github.event.schedule == '0 0 */5 * *'
      run: python run.py --title "$TITLE1" --content "$CONTENT" --days DAY1

    - name: Send msgs2
      if: github.event.schedule == '0 0 */7 * *'
      run: python run.py --title "$TITLE2" --content "$CONTENT" --days DAY2
